name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check patch
        run: |
          VERSION=6.2
          ./create-patch.sh "${VERSION}" actions-test.diff
          cmp --silent actions-test.diff "patch-${VERSION}.diff"

      - name: Repository Dispatch to home-manager-configurations
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Gerschtli/home-manager-configurations
          event-type: update-dwm
          client-payload: '{"commit_id": "${{ github.sha }}"}'
